import StableMatchingsE2E.StablePairMultigraph
import StableMatchingsE2E.StableEqualityBlocks
import StableMatchingsE2E.PopularRoommatesInterfaces
import StableMatchingsE2E.PartialMatching
import StableMatchingsE2E.StablePairComponents
import StableMatchingsE2E.StablePairBaseCases
import StableMatchingsE2E.StablePairConnected
import StableMatchingsE2E.StablePairCoefficients
import StableMatchingsE2E.StablePairNormalization
import StableMatchingsE2E.StablePairMatchedCoefficients
import StableMatchingsE2E.StablePairLowDegree
import StableMatchingsE2E.StablePairTwoNeighbors
import StableMatchingsE2E.StablePairEquality
import StableMatchingsE2E.StablePairShrinking
import StableMatchingsE2E.StableMatchingLattice
import StableMatchingsE2E.StableRotationSupport
import StableMatchingsE2E.StablePairApplication
import StableMatchingsE2E.StablePairEqualityApplication

-- Includes the universal multigraph SharpBound; the rotation bridge is separate.
open StableMatchingsE2E.LabeledMultigraph
#print axioms matchingCount_recurrence
#print axioms boundaryEdges_pair_card_add_twice_multiplicity
#print axioms doubleComponentCount_delete_singleton_le_degree
#print axioms doubleComponentCount_delete_pair_add_twice_multiplicity_le
#print axioms doubleComponentCount_eq_zero_of_cutConnected
#print axioms edgeCount_delete_pair_add_degrees
#print axioms vertexCount_delete_pair_add_two
#print axioms degree_eq_two_of_mem_doubleComponent
#print axioms degree_delete_singleton_add_multiplicity
#print axioms not_mem_doubleComponent_after_delete_of_degree_two
#print axioms doubleComponentCount_delete_le_one_of_unique_neighbor
#print axioms doubleComponentCount_delete_eq_zero_of_unique_degree_two_neighbor
#print axioms doubleComponentCount_le_card_of_vertex_witness
#print axioms exists_eligibleNeighbor_in_doubleComponent
#print axioms doubleComponentCount_delete_le_eligibleNeighbors_card
#print axioms exists_unique_neighbor_of_degree_one
#print axioms matchingCount_eq_mul_of_independent_partition
#print axioms matchingCount_eq_mul_of_empty_boundary
#print axioms doubleComponent_delete_iff_of_empty_boundary
#print axioms doubleComponentCount_add_of_empty_boundary
#print axioms vertexCount_add_of_partition
#print axioms edgeCount_add_of_empty_boundary
#print axioms sharpBound_of_empty_boundary
#print axioms matchingCount_eq_edgeCount_add_one_of_vertexCount_two
#print axioms doubleComponentCount_of_vertexCount_two
#print axioms two_vertex_uncorrected_arithmetic
#print axioms sharpBound_of_vertexCount_le_two
#print axioms degree_pos_of_cutConnected
#print axioms degree_lt_unique_neighbor_of_cutConnected
#print axioms exists_positive_min_degree_vertex
#print axioms exists_split_of_not_cutConnected
#print axioms sharpBound_from_connected_step
open StableMatchingsE2E.StablePairCoefficients
#print axioms t_fourth
#print axioms low_degree_one_two
#print axioms low_degree_one_large
#print axioms low_degree_two_no_high
#print axioms low_degree_two_one_high
#print axioms low_degree_two_two_high
#print axioms low_degree_two_unique
#print axioms highBound_lt
#print axioms integer_bound_iff_normalized
#print axioms sharpBound_iff_normalized
#print axioms normalized_delete_singleton_bound
#print axioms normalized_delete_pair_bound
#print axioms normalized_matching_recurrence
#print axioms normalized_unmatched_bound_of_cutConnected
#print axioms pairCoeff_eq
#print axioms pairCoeff_antitone_degree
#print axioms pairCoeff_high_multiple_neighbors
#print axioms pairCoeff_high_unique_neighbor
#print axioms normalized_pairCoeff_bound
#print axioms normalized_pair_high_bound
#print axioms sharpBound_connected_high_degree
#print axioms normalized_unique_neighbor_recurrence
#print axioms sharpBound_connected_degree_one
#print axioms sharpBound_connected_degree_two_unique
#print axioms eligibleNeighbors_subset_pair
#print axioms normalized_degree_two_simple_pair_bound
#print axioms sharpBound_connected_degree_two_distinct
#print axioms multiplicity_eq_one_of_two_distinct_neighbors
#print axioms sharpBound_connected_degree_two
#print axioms sharpBound
#print axioms normalized_strict_connected_high_degree
#print axioms normalized_strict_connected_degree_one
#print axioms normalized_strict_connected_degree_two_unique
#print axioms normalized_strict_connected_degree_two_distinct
#print axioms normalized_strict_connected_degree_two
#print axioms normalized_strict_of_cutConnected
#print axioms integer_equality_iff_normalized
#print axioms sharpEquality_iff_normalized
#print axioms not_sharpEquality_of_cutConnected
#print axioms two_vertex_uncorrected_strict
#print axioms sharpEquality_iff_of_vertexCount_two
#print axioms sharpEquality_iff_of_vertexCount_lt_two
#print axioms sharpEquality_iff_of_cutConnected
#print axioms sharpEquality_iff_of_empty_boundary
#print axioms sharpEquality_of_pairComponentDecomposition
#print axioms sharpEquality_iff_pairComponentDecomposition
#print axioms mem_omittedIncidences
#print axioms exists_omittedIncidence_touching
#print axioms touchedDoubleComponents_card_le_two
#print axioms doubleComponentCount_le_twice_omittedIncidences
#print axioms omittedIncidences_card_eq_excess
#print axioms doubleComponentCount_le_twice_excess
#print axioms originalMatchingFamily_subset
#print axioms originalMatchingCount_le
#print axioms original_incidence_cost
#print axioms originalMatching_fourth_bound
#print axioms StableMatchingsE2E.LabeledHypergraph.matchingCount_fourth_bound
#print axioms StableMatchingsE2E.LabeledHypergraph.matchingCount_fourth_le_two_pow
#print axioms StableMatchingsE2E.LabeledHypergraph.all_binary_of_matchingCount_fourth_eq
#print axioms StableMatchingsE2E.stable_swapSides
#print axioms StableMatchingsE2E.StableState.ext_rank
#print axioms StableMatchingsE2E.StableState.rank_better
#print axioms StableMatchingsE2E.StableState.rank_worse
#print axioms StableMatchingsE2E.StableState.changedMen_card_ge_two
#print axioms StableMatchingsE2E.StableState.rank_strict_of_le_of_changed
#print axioms StableMatchingsE2E.stableStateIdealEquiv
#print axioms StableMatchingsE2E.mem_stableStateIdealEquiv
#print axioms StableMatchingsE2E.stableStateIdealEquiv_injective
#print axioms StableMatchingsE2E.stableStateIdealEquiv_surjective
#print axioms StableMatchingsE2E.IrreducibleState.exists_predecessor
#print axioms StableMatchingsE2E.IrreducibleState.predecessor_lt
#print axioms StableMatchingsE2E.IrreducibleState.le_predecessor
#print axioms StableMatchingsE2E.IrreducibleState.predecessor_unique
#print axioms StableMatchingsE2E.IrreducibleState.support_card_ge_two
#print axioms StableMatchingsE2E.IrreducibleState.rank_predecessor_lt
#print axioms StableMatchingsE2E.IrreducibleState.le_iff_rank_le
#print axioms StableMatchingsE2E.IrreducibleState.comparable_of_mem_support
#print axioms StableMatchingsE2E.IrreducibleState.rank_eq_implies_eq_of_mem_support
#print axioms StableMatchingsE2E.IrreducibleState.exists_of_rank_increase
#print axioms StableMatchingsE2E.irreducibleSupport_overlap_comparable
#print axioms StableMatchingsE2E.attainedRanks_card_eq_partners
#print axioms StableMatchingsE2E.participantLabels_rank_image
#print axioms StableMatchingsE2E.participantLabels_card_add_one
#print axioms StableMatchingsE2E.support_incidence_double_count
#print axioms StableMatchingsE2E.mem_stablePairSet
#print axioms StableMatchingsE2E.stablePairSet_card
#print axioms StableMatchingsE2E.stablePairSet_card_eq_vertices_add_supports
#print axioms StableMatchingsE2E.StableState.swap_of_changedMen_pair
#print axioms StableMatchingsE2E.IrreducibleState.rank_predecessor_eq_of_no_between
#print axioms StableMatchingsE2E.IrreducibleState.no_consecutive_binary_same_support
#print axioms StableMatchingsE2E.isolated_binary_support_card_le_one
#print axioms StableMatchingsE2E.irreducibleSupport_no_isolated_double
#print axioms StableMatchingsE2E.FiniteIdealAntichain.mem_iff_below_maximal
#print axioms StableMatchingsE2E.FiniteIdealAntichain.maximals_antichain
#print axioms StableMatchingsE2E.FiniteIdealAntichain.maximals_injective
#print axioms StableMatchingsE2E.FiniteIdealAntichain.generated_maximals
#print axioms StableMatchingsE2E.FiniteIdealAntichain.maximals_generated
#print axioms StableMatchingsE2E.FiniteIdealAntichain.equiv
#print axioms StableMatchingsE2E.card_stableState
#print axioms StableMatchingsE2E.stableStateAntichainEquiv
#print axioms StableMatchingsE2E.stableCount_eq_antichainCount
#print axioms StableMatchingsE2E.stableCount_le_supportMatchingCount
#print axioms StableMatchingsE2E.stableCount_fourth_penalized_stablePairs
#print axioms StableMatchingsE2E.stableCount_fourth_le_two_pow_stablePairs
#print axioms isolatedSupport_lift_of_empty_boundary
#print axioms smallPairComponent_lift_of_empty_boundary
#print axioms exists_smallPairComponent_of_decomposition
#print axioms unique_incident_edge_of_sharpEquality
#print axioms StableMatchingsE2E.nonempty_stableState_of_stablePairEquality
#print axioms StableMatchingsE2E.supportExcess_eq_zero_of_stablePairEquality
#print axioms StableMatchingsE2E.all_supports_binary_of_stablePairEquality
#print axioms StableMatchingsE2E.binarySupportGraph_matchingCount
#print axioms StableMatchingsE2E.supportMatchingCount_eq_stableCount_of_equality
#print axioms StableMatchingsE2E.binarySupportGraph_sharpEquality
#print axioms StableMatchingsE2E.unique_support_label_of_stablePairEquality
#print axioms StableMatchingsE2E.irreducible_order_trivial_of_stablePairEquality
#print axioms StableMatchingsE2E.independentBinaryCover_of_stablePairEquality
#print axioms StableMatchingsE2E.stablePairEquality_of_independentBinaryCover
#print axioms StableMatchingsE2E.stablePairEquality_iff_independentBinaryCover
#print axioms StableMatchingsE2E.ideal_leastStableState
#print axioms StableMatchingsE2E.leastStableState_le
#print axioms StableMatchingsE2E.predecessor_eq_least_of_trivial_order
#print axioms StableMatchingsE2E.every_subset_antichain_of_trivial_order
#print axioms StableMatchingsE2E.equalityBooleanEquiv_bijective
#print axioms StableMatchingsE2E.femaleBlock_card
#print axioms StableMatchingsE2E.male_supports_disjoint_of_unique_cover
#print axioms StableMatchingsE2E.femaleBlocks_disjoint
#print axioms StableMatchingsE2E.femaleBlocks_cover
#print axioms StableMatchingsE2E.binary_label_swaps_base
#print axioms StableMatchingsE2E.mem_equalityBooleanEquiv
#print axioms StableMatchingsE2E.partner_of_equality_coordinate
#print axioms StableMatchingsE2E.all_subsets_realize_independent_swaps
#print axioms StableMatchingsE2E.AcceptableCompletion.stable_of_stablePerfect
#print axioms StableMatchingsE2E.AcceptableCompletion.stablePerfect_iff
#print axioms StableMatchingsE2E.AcceptableCompletion.count_le
#print axioms StableMatchingsE2E.popular_candidate_binomial
#print axioms StableMatchingsE2E.popular_base_certificate
#print axioms StableMatchingsE2E.PartialMatching.left_some_injective
#print axioms StableMatchingsE2E.RoommatesMatching.double_injective
#print axioms StableMatchingsE2E.roommates_double_stable_iff
#print axioms StableMatchingsE2E.roommates_stable_double_embedding
#print axioms StableMatchingsE2E.roommates_stable_count_le_double
