import StableMatchingsE2E.ConstantCertificate
#check Finset.prod_subtype
#check Fintype.prod_subtype
#check Finset.prod_erase_mul
#check Finset.mul_prod_erase
#check Finset.prod_bij
#check List.sum_ofFn
#check List.mapIdx_eq_ofFn
#check MeasureTheory.integral_map
#check MeasureTheory.MeasurePreserving.integral_comp
#check MeasureTheory.MeasurePreserving.integral_comp_emb
#check MeasureTheory.integrable_map_measure
#check MeasureTheory.Integrable.map
#check unitInterval.measurePreserving_coe
#check MeasureTheory.integral_Icc_eq_integral_Ioc
#check MeasureTheory.integral_Icc_eq_integral_Ioc'
#check measurable_of_finite
#check measurable_of_countable
#check integrable_of_finite
#check MeasureTheory.Integrable.of_finite
#check MeasureTheory.Integrable.of_bound
#check MeasureTheory.Integrable.bddAbove_range
#check MeasureTheory.lintegral_map
#check MeasureTheory.lintegral_map'
#check MeasureTheory.lintegral_countable'
#check ENNReal.ofReal_mul
#check ENNReal.ofReal_log
#check MeasureTheory.MeasurePreserving.lintegral_comp
#check MeasureTheory.lintegral_Icc_eq_lintegral_Ioc
#check MeasureTheory.lintegral_Icc_eq_lintegral_Ioc'
#check MeasureTheory.integrable_tsum
#check MeasureTheory.Integrable.tsum
#check MeasureTheory.ofReal_integral_eq_lintegral_ofReal
#check measurableSet_lt
#check MeasureTheory.lintegral_prod
#check MeasureTheory.lintegral_prod_symm
#check Finset.sum_lt_sum
#check Finset.sum_lt_sum_of_nonempty
#check MeasureTheory.lintegral_finset_sum
#check MeasureTheory.lintegral_const_mul
#check ENNReal.sum_lt_sum_of_nonempty
#check ENNReal.mul_lt_mul_left
#check ENNReal.inv_mul_cancel
#check ENNReal.ofReal_lt_ofReal_iff
#check ENNReal.ofReal_lt_ofReal_iff_of_nonneg
#check ENNReal.ofReal_strictMono
#check Equiv.sum_comp
#check Equiv.sum_comp_emb
#check List.getElem_mapIdx
#check List.get_mapIdx
#check List.mapIdx_eq_ofFn
